import { useState } from 'react';
import { ShieldCheck, UserPlus } from 'lucide-react';
import { ActionNotice, ErrorNotice, Loading, PageHeading, Panel, useAction, useResource, useTransitRefresh } from '../../components/transit/Shared';
import { patchTransit, postTransit, rows } from '../../services/transit';

export default function AccountsPage() {
  const accounts=useResource('/api/accounts');const fleet=useResource('/api/buses');const action=useAction();const refresh=useTransitRefresh();
  const [username,setUsername]=useState('');const [password,setPassword]=useState('');
  const [role,setRole]=useState('driver');const [busId,setBusId]=useState('BUS005');
  const [resetUser,setResetUser]=useState('');const [resetPassword,setResetPassword]=useState('');
  const create=async(event:React.FormEvent)=>{
    event.preventDefault();
    const saved=await action.run(()=>postTransit('/api/accounts',{username,password,role,bus_id:role==='driver'?busId:null}),'Account created.');
    if(saved){setUsername('');setPassword('');refresh();}
  };
  const reset=async()=>{const saved=await action.run(()=>patchTransit(`/api/accounts/${encodeURIComponent(resetUser)}`,{password:resetPassword}),'Password reset.');if(saved){setResetPassword('');refresh();}};
  return <div className="to-page"><PageHeading eyebrow="ADMINISTRATION" title="Users & access" description="Create assigned driver and head-office accounts. Public passengers use the navigation app without access to interior CCTV." actions={<ShieldCheck color="#00d9ff"/>}/><ActionNotice action={action}/><ErrorNotice message={accounts.error||fleet.error}/>
    <div className="to-grid"><Panel title="Create an account" subtitle="Only administrators can create or manage access."><form className="to-fields" onSubmit={create}><label className="to-field">Username<input aria-label="New username" minLength={3} maxLength={120} pattern="[a-zA-Z0-9_.-]+" required value={username} onChange={e=>setUsername(e.target.value)}/></label><label className="to-field">Password<input aria-label="New password" type="password" autoComplete="new-password" minLength={12} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)}/><small>At least 12 characters. Stored as a password hash.</small></label><label className="to-field">Role<select aria-label="New account role" value={role} onChange={e=>setRole(e.target.value)}><option value="driver">Driver / conductor</option><option value="head_office">Transport head office</option><option value="admin">Administrator</option></select></label>{role==='driver'&&<label className="to-field">Assigned bus<select aria-label="Assigned driver bus" value={busId} onChange={e=>setBusId(e.target.value)}>{rows(fleet.data?.buses).map(bus=><option key={bus.id} value={bus.id}>{bus.id} · {bus.registration_number??bus.route_id??'Reserve'}</option>)}</select></label>}<button className="to-button primary" disabled={action.busy||Boolean(accounts.error)}><UserPlus size={15}/>Create account</button></form></Panel>
    <Panel title="Registered accounts" subtitle="Passwords and hashes are never returned to this screen.">{accounts.loading?<Loading/>:<div className="to-data-table-wrap"><table className="to-data-table"><thead><tr><th>User</th><th>Role / bus</th><th>Access</th></tr></thead><tbody>{rows(accounts.data?.accounts).map(account=><tr key={account.username}><td>{account.username}</td><td>{account.role} {account.bus_id??''}</td><td><button className="to-button subtle" disabled={action.busy} onClick={()=>action.run(async()=>{const saved=await patchTransit(`/api/accounts/${encodeURIComponent(account.username)}`,{active:!account.active});refresh();return saved;},account.active?'Account disabled.':'Account enabled.')}>{account.active?'Disable':'Enable'}</button></td></tr>)}</tbody></table></div>}<div className="to-fields" style={{marginTop:20}}><label className="to-field">Reset account password<select aria-label="Password reset account" value={resetUser} onChange={e=>setResetUser(e.target.value)}><option value="">Select an account</option>{rows(accounts.data?.accounts).map(account=><option key={account.username} value={account.username}>{account.username}</option>)}</select></label><label className="to-field">New password<input aria-label="Reset password" type="password" autoComplete="new-password" minLength={12} maxLength={128} value={resetPassword} onChange={e=>setResetPassword(e.target.value)}/></label><button className="to-button" disabled={action.busy||!resetUser||resetPassword.length<12} onClick={reset}>Reset password</button></div><p className="to-note">The environment administrator account is configured in .env. Driver accounts can publish GPS only for their assigned bus. Account changes are audited.</p></Panel></div></div>;
}
