import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Camera, Gauge, MapPin } from 'lucide-react';
import { PageHeading, Panel, ErrorNotice, Loading } from '../../components/transit/Shared';
import { transitRequest, type Data } from '../../services/transit';
import './bus-speed.css';

export default function BusSpeedPage(){
  const [data,setData]=useState<Data|null>(null),[error,setError]=useState('');
  useEffect(()=>{
    let active=true,pending=false;
    const refresh=async()=>{if(pending)return;pending=true;try{const value=await transitRequest('/api/traffic/speed');if(active){setData(value);setError('');}}catch(e){if(active)setError((e as Error).message);}finally{pending=false;}};
    void refresh();const timer=window.setInterval(refresh,5000);return()=>{active=false;window.clearInterval(timer);};
  },[]);
  return <div className="to-page"><PageHeading eyebrow="MOVING BUS / ROAD ML" title="Bus speed & congestion" description="Combine GPS speed with YOLO counts from a forward-facing bus camera. Warn other journeys when sustained low speed and several vehicles suggest a queue." actions={<Link className="to-button" to="/fleet">Register bus road camera</Link>}/><ErrorNotice message={error}/>
    <Panel title="One phone, two inputs"><ol className="speed-instructions"><li>Open the assigned forward road camera below and aim it through the windscreen.</li><li>Allow camera access and start detection. Click Share bus GPS speed on the same page.</li><li>Keep the device aboard the assigned bus. Fresh GPS plus live vehicle counts update this screen and passenger route checks.</li></ol><p className="to-note">Speed is the bus's GPS estimate, not the speed of other vehicles seen by a moving camera. Interior passenger counts are a separate camera role.</p></Panel>
    {!data&&!error?<Loading/>:<div className="speed-grid">{(data?.cameras??[]).map((camera:Data)=><Panel key={camera.id} title={camera.name} subtitle={`${camera.bus_id} / ${camera.id}`}><div className="speed-reading"><Gauge/><strong>{camera.gps_speed?.available?`${camera.gps_speed.speed_kmh} km/h`:'Speed unavailable'}</strong><span>{camera.gps_speed?.source?.replaceAll('_',' ')}</span></div><p className="to-note">{camera.gps_speed?.reason??camera.gps_speed?.note}</p>{camera.gps_speed?.source==='gps_displacement_estimate'&&<p>GPS accuracy range: {camera.gps_speed.lower_speed_kmh}–{camera.gps_speed.upper_speed_kmh} km/h</p>}<div className={`speed-evidence ${camera.suspected_queue?'slow':''}`}><strong>{camera.suspected_queue?'Possible traffic queue':camera.state.replaceAll('_',' ')}</strong><p>{camera.live_evidence?`${camera.vehicle_count} vehicles visible | ${camera.slow_seconds}s sustained low speed`:'Start live road detection to collect current evidence.'}</p><small>{camera.live_evidence?`Scene pressure ${camera.congestion_score}/100`:'Recorded footage does not publish live alerts.'}</small></div><div className="speed-evidence"><strong>One-minute ML forecast</strong><p>{camera.prediction?.available?`${camera.prediction.predicted_score}/100 predicted pressure`:camera.prediction?.status?.replaceAll("_"," ")??"Waiting for live observations"}</p><small>{camera.prediction?.reason??camera.prediction?.note}</small>{camera.prediction?.history_seconds!=null&&<p>{Math.floor(camera.prediction.history_seconds/60)} / 10 minimum continuous minutes at this location</p>}{camera.prediction?.validation_mae!=null&&<p>Holdout MAE {camera.prediction.validation_mae}; persistence {camera.prediction.persistence_mae}</p>}</div><div className="speed-actions"><Link className="to-button primary" to={`/webcam?mode=general&camera_id=${encodeURIComponent(camera.id)}`}><Camera size={16}/>Camera + GPS</Link><Link className="to-button" to={`/passenger?bus_id=${encodeURIComponent(camera.bus_id)}`}><MapPin size={16}/>Plan from this bus</Link></div><small className="to-note">A slow bus may be at a signal or stop. This is a congestion warning, not proof of a blocked road.</small></Panel>)}</div>}
    {data&&!data.cameras?.length&&<Panel title="No bus road camera registered"><p>Register a camera with role Moving bus road and assign its bus in Fleet.</p></Panel>}
    <Panel title="How this changes routing and prediction"><p className="to-note">At least 3 visible vehicles, bus speed at most 10 km/h, 8 continuous seconds and multiple real GPS fixes raise a possible-queue warning. Stale, inaccurate or simulated GPS cannot trigger it. Warnings remain at the captured location for up to 20 seconds.</p><p className="to-note">Passenger route monitoring compares available road alternatives every five seconds. Following buses can plan from their GPS position and choose a destination. Official bus service changes still require operator review.</p><p className="to-note">The one-minute model now includes vehicle count and valid GPS speed. It still needs 10 minutes of continuous observations within 100 m and must beat its chronological baseline before any prediction is used. Moving between roads resets that learning window.</p></Panel>
  </div>;
}
