import { Link } from 'react-router-dom';
import { BrainCircuit, Camera, Smartphone, ShieldCheck } from 'lucide-react';
import ThemeToggle from '../../components/ThemeToggle';
import './ml.css';

export default function ConnectDevicePage() {
  const secure = window.isSecureContext;
  return <div className="ml-home"><header className="ml-app-header"><Link to="/" className="ml-logo"><BrainCircuit />TRANSITOPT <span>AI</span></Link><nav><Link to="/passenger">Travel</Link><Link to="/ml">Camera ML</Link><Link to="/admin">Admin</Link><ThemeToggle variant="compact" /></nav></header><main className="ml-connect"><span className="ml-eyebrow">LAPTOP + PHONE · SAME ML APP</span><h1>Connect a camera device</h1><div className="ml-connect-status"><ShieldCheck />{secure ? 'This browser has a secure connection. Camera permission can be requested.' : 'Open the app over trusted HTTPS to use this phone’s camera and GPS.'}</div><section><h2><Camera size={20} /> Laptop webcam</h2><p>Open the ML workspace on this laptop, choose Road traffic or Bus crowding, and select a registered camera. Click Open this device camera, allow camera access, then press Start Detection.</p><Link className="ml-primary" to="/ml">Open ML workspace</Link></section><section><h2><Smartphone size={20} /> Phone camera on the same Wi-Fi</h2><ol><li>On the laptop, run <code>Run-TransitOpt-Phone.bat start</code>. The launcher prints the laptop’s HTTPS address.</li><li>Transfer <code>data/phone_tls/transitopt-phone-ca.crt</code> to your own phone. Install it as a trusted CA certificate for this local project. On iPhone, enable full trust for the installed certificate in Certificate Trust Settings. No certificate is installed automatically.</li><li>Open the printed <code>https://LAPTOP-IP:8443</code> address in the phone browser. Both devices must be on the same Wi-Fi. Use a trusted connection without a certificate warning.</li><li>Open Camera ML and sign in with the admin account configured in the laptop’s <code>.env</code>. Choose the registered camera and use the Rear phone camera or Front camera option.</li><li>Keep this browser page open while detecting. ML runs on the laptop; the phone sends frames over the encrypted connection.</li></ol><p>Use <code>Run-TransitOpt-Phone.bat status</code> to see the address again, or <code>Run-TransitOpt-Phone.bat stop</code> to close phone access. If Wi-Fi blocks peer devices or the operating system blocks port 8443, the phone cannot reach the laptop.</p><p>Changing Wi-Fi may change the laptop IP; restart the phone launcher to refresh the certificate address. Phones do not use the laptop’s <code>127.0.0.1</code> address.</p></section><section><h2>Give the camera the right location</h2><p>For road traffic, register the camera’s actual signal latitude and longitude in Fleet before comparing nearby routes. For an interior camera, assign its bus ID. This location and assignment determine which passenger updates receive the ML output.</p><div className="ml-connect-links"><Link to="/fleet">Register / locate cameras</Link><Link to="/passenger">View passenger updates</Link><Link to="/models">Manage ML weights</Link></div></section></main></div>;
}
