import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { BrainCircuit, Camera, ArrowRight, Users, Smartphone, Gauge, Settings2 } from 'lucide-react';
import { PageHeading, Panel, ErrorNotice, Loading } from '../../components/transit/Shared';
import { transitRequest, type Data } from '../../services/transit';
import './ml.css';

export default function MLWorkspacePage() {
  const [data, setData] = useState<Data | null>(null), [error, setError] = useState('');
  const [role, setRole] = useState('road_traffic'), [cameraId, setCameraId] = useState('');
  const [latitude,setLatitude]=useState(''), [longitude,setLongitude]=useState(''), [locationNotice,setLocationNotice]=useState('');
  const [saving,setSaving]=useState(false);
  useEffect(() => {
    let active = true, pending = false;
    async function refresh() { if (pending) return; pending = true; try { const next = await transitRequest('/api/ml/overview'); if (active) { setData(next); setError(''); } } catch (e) { if (active) setError((e as Error).message); } finally { pending = false; } }
    refresh(); const timer = window.setInterval(refresh, 5000);
    return () => { active = false; window.clearInterval(timer); };
  }, []);
  const cameras: Data[] = (data?.cameras ?? []).filter((c: Data) => c.role===role);
  const selected = cameras.find(c => c.id===cameraId) ?? cameras[0];
  const road = (data?.road_cameras ?? []).find((c: Data) => c.id===selected?.id);
  useEffect(() => {setLatitude(selected?.latitude?.toString() ?? '');setLongitude(selected?.longitude?.toString() ?? '');setLocationNotice('');}, [selected?.id]);
  async function saveLocation() {
    if (!selected || !latitude.trim() || !longitude.trim()) return;
    setSaving(true); setLocationNotice('');
    try { await transitRequest(`/api/traffic/cameras/${selected.id}/location`,{method:'PUT',body:JSON.stringify({latitude:Number(latitude),longitude:Number(longitude)})});setLocationNotice('Camera location saved. Passenger route monitoring uses this position.'); }
    catch(e) {setLocationNotice((e as Error).message);} finally {setSaving(false);}
  }
  const model = (data?.models?.detection_models ?? []).find((m: Data) => m.type===(role==='bus_interior'?'human':'general') && m.is_default);
  return <div className="to-page"><PageHeading eyebrow="MAIN ML PROJECT" title="Camera ML workspace" description="Run the existing detection models on your laptop webcam or phone camera. Every registered camera has one clear job." actions={<Link className="to-button" to="/connect"><Smartphone size={16} />Connect phone</Link>} /><ErrorNotice message={error} />{!data ? <Loading /> : <>
    <div className="ml-use-tabs" role="group" aria-label="Camera ML use case"><button className={role==='road_traffic'?'active':''} onClick={() => {setRole('road_traffic');setCameraId('');}}><Camera /><div><strong>Fixed road camera</strong><span>Vehicles → pressure forecast → route alerts</span></div></button><button className={role==='bus_road'?'active':''} onClick={()=>{setRole('bus_road');setCameraId('');}}><Gauge/><div><strong>Moving bus road camera</strong><span>Outside vehicles + bus GPS speed</span></div></button><button className={role==='bus_interior'?'active':''} onClick={() => {setRole('bus_interior');setCameraId('');}}><Users /><div><strong>Inside the bus</strong><span>Visible people → crowd level → passenger view</span></div></button></div>
    <div className="to-grid map-split"><Panel title="Connect and analyze" subtitle="Laptop and phone use the same server-side ML models"><label className="to-field">Registered camera<select aria-label="Registered ML camera" value={selected?.id ?? ''} onChange={e => setCameraId(e.target.value)}>{cameras.map(c => <option key={c.id} value={c.id}>{c.name} · {c.id}{c.bus_id ? ` · ${c.bus_id}` : ''}</option>)}</select></label><div className="ml-camera-state"><span className={`to-status ${selected?.status==='online'?'low':''}`}>{selected?.status?.replaceAll('_',' ') ?? 'No camera registered'}</span><span>{selected?.last_processed_at ? `Last analyzed ${new Date(selected.last_processed_at).toLocaleTimeString()}` : 'Waiting for camera frames'}</span></div><div className="ml-actions">{selected && <Link className="to-button primary" to={`/webcam?mode=${role==='bus_interior'?'human':'general'}&camera_id=${selected.id}`}><Camera size={16} />Open this device camera<ArrowRight size={15} /></Link>}<Link className="to-button" to="/cctv">Analyze a recording</Link><Link className="to-button" to="/fleet"><Settings2 size={15} />Register / locate camera</Link></div>{role==='bus_road'&&<p className="to-note">Aim the rear camera at the road, start detection and click Share bus GPS speed on that page. Open Bus speed and congestion to inspect results.</p>}<ol className="ml-steps"><li>Choose a registered road camera or bus interior camera.</li><li>Open the device camera and allow camera access. On a phone, choose the rear or front camera.</li><li>Press Start Detection. Passenger updates use the registered camera location or bus assignment.</li></ol><p className="to-note">A road camera needs its actual signal location configured in Fleet. Existing demo pins are approximate. A moving bus road camera pairs visible vehicles with bus GPS; an interior camera counts visible people.</p></Panel>
      <Panel title="Active ML model" subtitle="Model identity and prediction quality"><div className="ml-model-info"><BrainCircuit /><div><strong>{model?.filename ?? 'No default detection model'}</strong><span>{model?.weights_available ? 'Weights available' : 'Weights unavailable'} · {role==='bus_interior'?'Person-only bus detection':'General vehicle detection'}</span><small>{model?.name}</small></div></div><Link className="to-button" to="/models">Manage / update model weights</Link><Link className="to-button" to="/speed"><Gauge size={16}/>Bus speed and congestion</Link>{role!=='bus_interior' ? <div className="ml-prediction"><h3><Gauge size={18} />One-minute traffic scene forecast</h3><strong>{road?.prediction?.available ? `${road.prediction.predicted_score}/100 predicted scene pressure` : road?.prediction?.status?.replaceAll('_',' ') ?? 'Waiting for live camera'}</strong><p>{road?.prediction?.reason ?? road?.prediction?.note ?? 'Learns from ten continuous minutes of this camera’s live YOLO vehicle observations.'}</p>{road?.prediction?.history_seconds != null && <p>Live history: {Math.floor(road.prediction.history_seconds/60)} / 10 minimum minutes</p>}{road?.prediction?.validation_mae != null && <p>Holdout MAE {road.prediction.validation_mae} · persistence baseline {road.prediction.persistence_mae}</p>}<small>A forecast affects ranking only after it beats the baseline. Scene pressure is a count estimate; route comparison weights are not measured travel delay.</small></div> : <div className="ml-prediction"><h3><Users size={18} />Visible people, separate from road traffic</h3><p>Person-only detection feeds the assigned bus crowd indicator. Partial camera coverage cannot establish total occupancy.</p><Link className="to-button" to="/fleet">View bus crowding</Link></div>}</Panel></div>
    {role==='road_traffic' && selected?.role==='road_traffic' && <Panel title="Signal camera location" subtitle="Administrator configuration · set the actual camera position"><p className="to-note">Current source: {selected.coordinate_source?.replaceAll('_',' ')}. Nearby route matching uses a 250 m camera neighborhood.</p><form onSubmit={e=>{e.preventDefault();void saveLocation();}}><div className="to-form-row"><label className="to-field">Camera latitude<input required type="number" step="any" min={-90} max={90} value={latitude} onChange={e=>setLatitude(e.target.value)}/></label><label className="to-field">Camera longitude<input required type="number" step="any" min={-180} max={180} value={longitude} onChange={e=>setLongitude(e.target.value)}/></label></div><button className="to-button primary" disabled={saving} style={{marginTop:16}}>{saving?'Saving…':'Save signal location'}</button></form>{locationNotice && <p role="status" className="to-note">{locationNotice}</p>}</Panel>}
    <Panel title="ML output reaches the same app" subtitle="Live observations refresh passenger route monitoring every five seconds"><div className="ml-output-row"><Link to="/passenger"><MapIcon />Passenger routes & traffic alerts<ArrowRight size={16} /></Link><Link to="/fleet"><Users size={19} />Bus crowding & GPS<ArrowRight size={16} /></Link><Link to="/safety"><Camera size={19} />Review bus safety signals<ArrowRight size={16} /></Link></div></Panel>
  </>}</div>;
}
function MapIcon() { return <Gauge size={19} />; }
