import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { CircleMarker, MapContainer, Popup, TileLayer } from 'react-leaflet';
import { Bell, BusFront, Camera, Download, MapPin, RefreshCw, ShieldCheck } from 'lucide-react';
import { ActionNotice, Empty, ErrorNotice, Loading, Metric, PageHeading, Panel, useAction, useResource, useTransitRefresh } from '../../components/transit/Shared';
import { postTransit, rows, timeText, transitRequest, type Data } from '../../services/transit';
import 'leaflet/dist/leaflet.css';

export function FleetPage() {
  const buses = useResource('/api/buses'); const cameras = useResource('/api/mobility/cameras'); const summary = useResource('/api/dashboard/overview');
  const action = useAction(); const invalidate = useTransitRefresh();
  const [busId, setBusId] = useState('BUS005'); const [registration, setRegistration] = useState('TN30-N-1234');
  const [capacity, setCapacity] = useState(50); const [operator, setOperator] = useState('');
  const [cameraId, setCameraId] = useState('BUS_CAM_001'); const [cameraName, setCameraName] = useState('Demo bus interior webcam');
  const [cameraBus, setCameraBus] = useState('BUS005'); const [cameraRole, setCameraRole] = useState<'bus_interior' | 'road_traffic' | 'bus_road'>('bus_interior');
  const [lat, setLat] = useState(''); const [lon, setLon] = useState('');
  const fleet = rows(buses.data?.buses); const registered = fleet.filter(bus => bus.registration_number);
  const live = fleet.filter(bus => bus.location?.fresh);
  const saveBus = async () => { const saved = await action.run(() => postTransit('/api/buses/register', { bus_id: busId, registration_number: registration.toUpperCase(), route_id: fleet.find(bus => bus.id === busId)?.route_id ?? null, capacity, operator_name: operator || null } ), 'Bus registration saved.'); if (saved) invalidate(); };
  const saveCamera = async () => { const saved = await action.run(() => postTransit('/api/cameras/register', { id: cameraId.toUpperCase(), name: cameraName, role: cameraRole, bus_id: cameraRole !== 'road_traffic' ? cameraBus : null, stop_id: 'S02', corridor_id: 'C02', latitude: cameraRole==='road_traffic' && lat ? Number(lat) : null, longitude: cameraRole==='road_traffic' && lon ? Number(lon) : null, source_type: 'browser_camera_or_upload', coordinate_source: 'operator_configured' }), 'Camera registered.'); if (saved) invalidate(); };
  return <div className="to-page"><PageHeading eyebrow="HEAD OFFICE · FLEET CONTROL" title="Live bus operations" description="Registered vehicles, camera associations and the latest genuine GPS and camera observations." actions={<><Link className="to-button" to="/passenger"><MapPin size={14} />Passenger view</Link><button className="to-button subtle" onClick={() => { buses.refresh(); cameras.refresh(); summary.refresh(); }}><RefreshCw size={14} />Refresh</button></>} />
    <ActionNotice action={action} /><ErrorNotice message={buses.error || cameras.error || summary.error} />
    <div className="to-grid four"><Metric label="Registered buses" value={registered.length} icon={<BusFront />} /><Metric label="Fresh GPS reports" value={summary.data?.gps_live ?? '—'} detail="Last 90 seconds; source shown in bus details" icon={<MapPin />} accent="emerald" /><Metric label="Fresh crowd observations" value={summary.data?.camera_crowding_fresh ?? '—'} detail="Visible people, past 5 minutes" icon={<Camera />} accent="purple" /><Metric label="Alerts awaiting review" value={summary.data?.alerts_awaiting_review ?? '—'} icon={<Bell />} accent="orange" /></div>
    <div className="to-grid map-split"><Panel title="Geolocated fleet" subtitle="Only fresh GPS points appear. Demo GPS points are marked in each bus detail."><div style={{ height: 375, borderRadius: 8, overflow: 'hidden' }}><MapContainer center={[11.6649, 78.146]} zoom={12} style={{ height: '100%', width: '100%' }}><TileLayer attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>' url="https://tile.openstreetmap.org/{z}/{x}/{y}.png" />{live.map(bus => <CircleMarker key={bus.id} center={[bus.location.latitude, bus.location.longitude]} radius={10} pathOptions={{ color: '#ffffff', fillColor: '#00b9db', fillOpacity: 1, weight: 2 }}><Popup><strong>{bus.registration_number ?? bus.id}</strong><br />{bus.route_id} · {bus.location.source}<br />GPS {timeText(bus.location.timestamp)}<br />Crowding {bus.crowding?.fresh ? bus.crowding.level : 'Unavailable'}</Popup></CircleMarker>)}</MapContainer></div><p className="to-note">The existing schematic network remains illustrative. These markers use stored coordinates with timestamps and source labels.</p></Panel>
      <Panel title="Bus and camera status" subtitle="Actual reports only; missing location is shown as unavailable">{buses.loading && !buses.data ? <Loading /> : <div className="to-stack" style={{ maxHeight: 430, overflowY: 'auto' }}>{registered.map(bus => <div key={bus.id} className="to-recommendation"><strong>{bus.registration_number} · {bus.id}</strong><p>{bus.route_id ?? 'No route'} · GPS {bus.tracking_status} · {bus.crowding?.fresh ? `${bus.crowding.visible_people} people visible · ${bus.crowding.level}` : 'No fresh camera crowding'}</p><small className="to-small">{bus.location?.source ?? 'No GPS source'} · {bus.public_safety_status}</small></div>)}</div>}</Panel></div>
    <div className="to-grid"><Panel title="Register a bus" subtitle="Assign a registration to an existing fleet ID; service allocations stay under operator approval."><div className="to-fields"><label className="to-field">Fleet bus ID<select value={busId} onChange={e => { setBusId(e.target.value); const found = fleet.find(b => b.id === e.target.value); setRegistration(found?.registration_number ?? ''); setCapacity(found?.capacity ?? 50); }}>{fleet.map(bus => <option key={bus.id} value={bus.id}>{bus.id} · {bus.route_id ?? 'Reserve'}</option>)}</select></label><label className="to-field">Registration number<input value={registration} onChange={e => setRegistration(e.target.value.toUpperCase())} /></label><label className="to-field">Permitted passenger capacity<input type="number" min={1} max={150} value={capacity} onChange={e => setCapacity(Number(e.target.value))} /></label><label className="to-field">Operator name<input value={operator} onChange={e => setOperator(e.target.value)} /></label><button className="to-button primary" disabled={action.busy || !registration} onClick={saveBus}>Save bus registration</button></div></Panel>
      <Panel title="Register a camera" subtitle="Map an authorized source to one bus interior or a road corridor."><div className="to-fields"><label className="to-field">Camera ID<input value={cameraId} onChange={e => setCameraId(e.target.value.toUpperCase())} /></label><label className="to-field">Name<input value={cameraName} onChange={e => setCameraName(e.target.value)} /></label><label className="to-field">Role<select value={cameraRole} onChange={e => setCameraRole(e.target.value as typeof cameraRole)}><option value="bus_interior">Bus interior</option><option value="road_traffic">Fixed road traffic</option><option value="bus_road">Moving bus road</option></select></label>{cameraRole !== 'road_traffic' ? <label className="to-field">Assigned bus<select value={cameraBus} onChange={e => setCameraBus(e.target.value)}>{registered.map(bus => <option key={bus.id} value={bus.id}>{bus.id} · {bus.registration_number}</option>)}</select></label> : <div className="to-form-row"><label className="to-field">Latitude<input type="number" step="any" value={lat} onChange={e => setLat(e.target.value)} /></label><label className="to-field">Longitude<input type="number" step="any" value={lon} onChange={e => setLon(e.target.value)} /></label></div>}<button className="to-button primary" disabled={action.busy || !cameraId || !cameraName} onClick={saveCamera}>Register camera</button></div><p className="to-note">Browser camera activation needs device permission. Authorized IP/RTSP ingestion remains unavailable.</p></Panel></div>
    <Panel title="Camera associations"><div className="to-data-table-wrap"><table className="to-data-table"><thead><tr><th>Camera</th><th>Role</th><th>Bus / corridor</th><th>Status</th><th>Input</th></tr></thead><tbody>{rows(cameras.data?.cameras).map(camera => <tr key={camera.id}><td>{camera.id} · {camera.name}</td><td>{camera.role.replaceAll('_', ' ')}</td><td>{camera.bus_id ?? camera.corridor_id}</td><td>{camera.status.replaceAll('_', ' ')}<small className="to-small" style={{display:'block'}}>{timeText(camera.last_processed_at)}</small></td><td><Link to={`/webcam?camera_id=${camera.id}&mode=${camera.role === 'bus_interior' ? 'human' : 'general'}`}>Open webcam</Link><button className="to-button subtle" style={{marginLeft:10}} disabled={action.busy} onClick={()=>action.run(async()=>{const saved=await postTransit(`/api/cameras/${camera.id}/stop`);invalidate();return saved;},'Camera stop requested.')}>Stop</button></td></tr>)}</tbody></table></div></Panel>
  </div>;
}

export function SafetyPage() {
  const alerts = useResource('/api/alerts'); const cameras = useResource('/api/mobility/cameras'); const action = useAction(); const invalidate = useTransitRefresh();
  const [selectedCamera, setSelectedCamera] = useState('BUS_CAM_001'); const [zone, setZone] = useState([0, 0, .25, 1]);
  const [notes, setNotes] = useState<Record<string, string>>({});
  const interior = rows(cameras.data?.cameras).filter(camera => camera.role === 'bus_interior');
  const selected = interior.find(camera => camera.id === selectedCamera);
  useEffect(() => { if (selected?.safety_zone) setZone(selected.safety_zone); }, [selected?.id, JSON.stringify(selected?.safety_zone)]);
  useEffect(() => { const timer = window.setInterval(() => alerts.refresh(), 5000); return () => window.clearInterval(timer); }, []);
  async function saveZone() { const result = await action.run(() => transitRequest(`/api/mobility/cameras/${selectedCamera}`, { method: 'PATCH', body: JSON.stringify({ safety_zone: zone, door_open: selected?.door_open ?? null }) }), 'Safety zone saved.'); if (result) invalidate(); }
  async function review(id: string, command: string) { const result = await action.run(() => postTransit(`/api/alerts/${id}/${command}`, { note: notes[id] ?? '' }), `Alert ${command.replace('-', ' ')} recorded.`); if (result) invalidate(); }
  async function download() { const response = await transitRequest('/api/alerts'); const data = rows(response.alerts); const fields = ['id', 'bus_id', 'camera_id', 'timestamp', 'category', 'severity', 'status', 'note']; const quote = (value: unknown) => `"${String(value ?? '').replace(/"/g, '""')}"`; const blob = new Blob([[fields.join(','), ...data.map(row => fields.map(field => quote(row[field])).join(','))].join('\n')], { type: 'text/csv' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'transitopt-alerts.csv'; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 1000); }
  return <div className="to-page"><PageHeading eyebrow="HEAD OFFICE · PASSENGER SAFETY" title="Review safety signals" description="Suspected doorway events require repeated model observations, a configured zone, moving GPS, and an open door report." actions={<button className="to-button subtle" onClick={download}><Download size={14} />Export incidents</button>} /><ActionNotice action={action} /><ErrorNotice message={alerts.error || cameras.error} />
    <div className="to-grid map-split"><Panel title="Incident queue" subtitle="Immediate in-app polling · human review required">{alerts.loading && !alerts.data ? <Loading /> : rows(alerts.data?.alerts).length ? <div className="to-stack">{rows(alerts.data?.alerts).map(event => <div className="to-recommendation" key={event.id}><div className="to-rec-header"><strong>{event.registration_number ?? event.bus_id} · {event.category.replaceAll('_', ' ')}</strong><span className={`to-status ${event.status === 'awaiting_review' ? 'high' : ''}`}>{event.status.replaceAll('_', ' ')}</span></div><p>{event.camera_name ?? event.camera_id} · {timeText(event.timestamp)} · {event.severity} · {event.delivery.replaceAll('_', ' ')}</p><p>Last bus GPS: {event.last_known_location ? `${event.last_known_location.latitude.toFixed(5)}, ${event.last_known_location.longitude.toFixed(5)} · ${event.last_known_location.fresh ? 'fresh' : 'stale'} · ${event.last_known_location.source}` : 'unavailable'}</p><details><summary className="to-small">Evidence and rule context</summary><pre className="to-code">{JSON.stringify(event.evidence, null, 2)}</pre></details>{!['resolved', 'false_positive'].includes(event.status) && <><label className="to-field" style={{ margin: '13px 0' }}>Review note<textarea value={notes[event.id] ?? ''} maxLength={1000} onChange={e => setNotes(current => ({ ...current, [event.id]: e.target.value }))} /></label><div className="to-action-row"><button className="to-button" disabled={action.busy || event.status === 'acknowledged'} onClick={() => review(event.id, 'acknowledge')}>Acknowledge</button><button className="to-button success" disabled={action.busy} onClick={() => review(event.id, 'resolve')}>Resolve</button><button className="to-button subtle" disabled={action.busy} onClick={() => review(event.id, 'false-positive')}>False positive</button></div></>}</div>)}</div> : <Empty title="No safety incidents" description="A configured doorway zone must contain a detected person for three consecutive frames while fresh GPS reports movement and the door is reported open." />}</Panel>
      <Panel title="Doorway safety zone" subtitle="Normalized image coordinates · configured by head office"><label className="to-field">Interior camera<select value={selectedCamera} onChange={e => setSelectedCamera(e.target.value)}>{interior.map(camera => <option value={camera.id} key={camera.id}>{camera.name} · {camera.bus_id}</option>)}</select></label><div className="to-form-row" style={{ margin: '16px 0' }}>{['X', 'Y', 'Width', 'Height'].map((label, index) => <label className="to-field" key={label}>{label}<input type="number" min={0} max={1} step={.05} value={zone[index]} onChange={e => setZone(values => values.map((value, i) => i === index ? Number(e.target.value) : value))} /></label>)}</div><button className="to-button primary" disabled={action.busy || !selected} onClick={saveZone}>Save zone</button><p className="to-note">Footpoints inside the zone count as a possible risk. This does not prove someone is outside the bus. A driver must separately report door state; GPS must show movement before an alert can be created.</p><div className="to-insight" style={{ marginTop: 18 }}><ShieldCheck size={22} /><div><strong>Evidence retention</strong><p>Incident records store detection metadata and rule context. Evidence frames are unavailable in this prototype, so review the source recording with authorized access when needed.</p></div></div></Panel></div>
  </div>;
}
