import { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { Activity, ArrowDownRight, ArrowRight, ArrowUpRight, BusFront, Check, ChevronRight, Clock3, Download, GitBranch, Info, Layers, Loader2, MapPin, Play, ShieldCheck, SlidersHorizontal, Sparkles, Users, X } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import TransitMap from '../../components/transit/TransitMap';
import { ActionNotice, Empty, ErrorNotice, Loading, Metric, PageHeading, Panel, RefreshButton, SourceBadge, chartTooltip, useAction, useResource, useTransitRefresh } from '../../components/transit/Shared';
import { exportTransit, numberText, numeric, postTransit, rows, timeText, transitRequest, type Data, type Network } from '../../services/transit';

function RoutePlanTable({ plan, network }: { plan: Data; network?: Network }) {
  return <div className="to-data-table-wrap"><table className="to-data-table"><thead><tr><th>Route</th><th>Current → proposed</th><th>Variant</th><th>Headway</th><th>Forecast</th><th>Capacity</th><th>Unserved</th></tr></thead><tbody>{rows(plan.routes).map(row => {
    const route = network?.routes.find(r => r.id === row.route_id);
    return <tr key={row.route_id}><td><strong className="to-route-label"><i style={{ background: route?.color }} />{row.route_id}</strong></td><td>{row.previous_buses ?? route?.current_buses ?? '—'} <span className="to-small">→</span> <strong>{row.buses} buses</strong></td><td>{row.variant_id === 'alternative' ? 'Alternative corridor' : 'Existing corridor'}</td><td>{numberText(row.headway_minutes, 1)} min</td><td>{numberText(row.demand)}</td><td>{numberText(row.capacity)}</td><td className={row.unserved_demand ? 'to-warning-text' : 'to-success-text'}>{numberText(row.unserved_demand)}</td></tr>;
  })}</tbody></table></div>;
}
export function ComparisonPanel({ result }: { result: Data }) {
  const before = result.baseline?.totals ?? result.baseline?.metrics ?? {};
  const after = result.totals ?? result.optimized?.totals ?? {};
  const fields = [['average_wait_minutes', 'Average waiting time', ' min'], ['capacity_shortfall', 'Unserved demand', ' boardings'], ['average_delay_minutes', 'Traffic-related delay', ' min'], ['demand_coverage_pct', 'Demand coverage', '%'], ['fleet_utilization_pct', 'Operational fleet use', '%'], ['operating_cost_inr', 'Operating cost', ' INR']];
  const chart = fields.slice(0, 1).concat(fields.slice(2, 3)).map(([key, label]) => ({ metric: label === 'Average waiting time' ? 'Wait' : 'Delay', Baseline: before[key], Optimized: after[key] }));
  return <Panel title="Baseline vs. optimized service" subtitle="Same demand, traffic, fleet, capacity and horizon assumptions" actions={<SourceBadge source="OPTIMIZATION_RESULT" />}>
    <div className="to-comparison">{[['BASELINE PLAN', before], ['OPTIMIZED PLAN', after]].map(([label, metrics]) => <div key={String(label)}><h3>{String(label)}</h3><dl>{fields.map(([key, title, unit]) => <div key={key}><dt>{title}</dt><dd>{numberText((metrics as Data)[key], key.includes('minutes') || key.includes('pct') ? 1 : 0)}{(metrics as Data)[key] == null ? '' : unit}</dd></div>)}</dl></div>)}</div>
    {result.feasible && <div className="to-chart" style={{ height: 150, marginTop: 20 }}><ResponsiveContainer><BarChart data={chart} barGap={6}><CartesianGrid stroke="#193753" vertical={false} /><XAxis dataKey="metric" tick={{ fill: '#86a5be', fontSize: 10 }} /><YAxis unit="m" tick={{ fill: '#668da9', fontSize: 9 }} /><Tooltip contentStyle={chartTooltip} /><Legend wrapperStyle={{ fontSize: 9 }} /><Bar dataKey="Baseline" fill="#2b5070" radius={[3, 3, 0, 0]} maxBarSize={45} /><Bar dataKey="Optimized" fill="#00e5a0" radius={[3, 3, 0, 0]} maxBarSize={45} /></BarChart></ResponsiveContainer></div>}
    <p className="to-note">Waiting assumes uniform arrivals and covers served demand. Delay, cost and service improvements are simulated estimates. The optimizer minimizes the weighted objective; every individual metric need not improve.</p>
  </Panel>;
}
function RunResult({ result, network }: { result: Data; network?: Network }) {
  if (!result.feasible) return <Panel title="No feasible operating plan" subtitle={`CP-SAT status: ${result.solver_status}`}><ErrorNotice message={rows(result.warnings).length ? result.warnings.join(' ') : (result.warnings ?? ['No plan satisfies the selected hard constraints.']).join(' ')} /><p className="to-description">Increase the operational fleet, reduce reserves, or revise maximum headway requirements. The system has saved this scenario for review and generated no route recommendations.</p>{result.minimum_required_buses != null && <div className="to-details"><div><dt>Minimum buses required by headway</dt><dd>{result.minimum_required_buses}</dd></div><div><dt>Operational buses supplied</dt><dd>{numeric(result.config?.fleet_size) - numeric(result.config?.reserve_fleet)}</dd></div></div>}</Panel>;
  const totals = result.totals ?? {};
  return <div className="to-page"><div className="to-grid four"><Metric label="Allocated buses" value={numberText(totals.allocated_buses)} detail={`${totals.reserve_fleet} reserved · ${totals.unused_operational_buses} operational spare`} icon={<BusFront />} /><Metric label="Demand coverage" value={numberText(totals.demand_coverage_pct, 1)} unit="%" accent="emerald" detail="Forecast boardings served within horizon" /><Metric label="Unserved demand" value={numberText(totals.capacity_shortfall)} accent="orange" detail="Explicit capacity shortfall" /><Metric label="Average wait" value={numberText(totals.average_wait_minutes, 1)} unit="min" detail="Modeled wait for served passengers" icon={<Clock3 />} /></div>
    <Panel title="Recommended route allocations" subtitle={`Solver: ${result.solver_status} · ${numberText(result.wall_time_seconds, 2)}s · ${result.config?.horizon_minutes ?? 60}-minute horizon`} actions={<SourceBadge source="OPTIMIZATION_RESULT" />}><RoutePlanTable plan={result} network={network} /></Panel>
    <div className="to-grid"><ComparisonPanel result={result} /><Panel title="Why this recommendation?" subtitle="Reasons from the selected solver options, not fixed advice"><div className="to-stack">{rows(result.routes).filter(row => row.changed).map(row => <div key={row.route_id} className="to-rec-evidence"><strong>{row.route_id} · {row.previous_buses} → {row.buses} buses</strong><p>{row.reason}</p></div>)}</div><details className="to-small" style={{ marginTop: 16 }}><summary>Constraint verification and assumptions</summary>{rows(result.constraints).map((constraint, index) => <div className="to-bullet" key={index}>{constraint.satisfied ? <Check /> : <X />}<span>{constraint.name}: {constraint.detail}</span></div>)}<ul className="to-list">{(result.assumptions ?? []).map((assumption: string) => <li key={assumption}>{assumption}</li>)}</ul></details></Panel></div>
    {network && <Panel title="Route transformation" subtitle="Colored lines: current network · white dashed lines: solver-selected variants"><TransitMap network={network} plan={result} traffic={network.corridors} /></Panel>}
    <div className="to-insight"><ShieldCheck size={24} /><div><strong>Ready for operator review</strong><p>Recommendations remain pending until reviewed. The complete plan must be approved before simulated activation, and the server verifies fleet consistency again at activation.</p><Link className="to-button primary" style={{ marginTop: 13 }} to={`/recommendations?run=${result.id ?? result.run_id}`}>Review recommendations <ArrowRight size={13} /></Link></div></div>
  </div>;
}

export function DashboardPage() {
  const summary = useResource('/api/dashboard/summary'); const network = useResource<Network>('/api/network'); const history = useResource('/api/demand/history?route_id=R02&limit=24');
  const action = useAction(); const refresh = useTransitRefresh(); const navigate = useNavigate();
  const data = summary.data; const kpis = data?.kpis ?? {}; const traffic = rows(data?.traffic); const recs = rows(data?.recommendations);
  const chartData = rows(history.data?.history ?? history.data?.items).map(row => ({ time: row.timestamp, demand: row.boarding_demand ?? row.passengers ?? row.demand }));
  const runOptimization = async () => { const result = await action.run(() => postTransit('/api/optimization/run', { name: 'Operator dashboard scenario' })); if (result) { refresh(); navigate(`/optimization?run=${result.id}`); } };
  return <><PageHeading eyebrow="SALEM OPERATIONS WORKSPACE" title="Plan better journeys." description="Vision intelligence, passenger demand and service decisions in one connected workspace." actions={<><button className="to-button subtle" onClick={() => action.run(() => exportTransit('traffic'))}><Download size={14} /> Export data</button><button className="to-button primary" disabled={action.busy || !data} onClick={runOptimization}>{action.busy ? <Loader2 className="animate-spin" size={14} /> : <Sparkles size={14} />} Run optimization</button></>} /><ActionNotice action={action} /><ErrorNotice message={summary.error || network.error} retry={() => { summary.refresh(); network.refresh(); }} />
    {summary.loading && !data ? <Loading label="Loading the seeded transit scenario and model forecasts…" /> : data && <>
      <div className="to-kpis"><Metric label="Available buses" value={numberText(kpis.available_buses)} detail={`${kpis.reserve_buses} reserved for operational resilience`} icon={<BusFront />} /><Metric label="Allocated buses" value={numberText(kpis.allocated_buses)} detail="Current simulated route assignments" icon={<Layers />} /><Metric label="Forecast passenger demand" value={numberText(kpis.forecast_passenger_demand)} detail={`ML forecast · next ${data.settings?.horizon_minutes ?? 60} minutes`} icon={<Users />} accent="purple" /><Metric label="Capacity shortfall" value={numberText(kpis.capacity_shortfall)} detail="Current plan · unserved forecast boardings" icon={<Activity />} accent="orange" /></div>
      <div className="to-mini-kpis"><div><small>AVERAGE WAIT · SIMULATED</small><strong>{numberText(kpis.average_waiting_time_minutes, 1)} <span className="to-small">min</span></strong></div><div><small>TOTAL FLEET UTILIZATION</small><strong>{numberText(kpis.fleet_utilization_pct, 1)} <span className="to-small">%</span></strong></div><div><small>HIGH CONGESTION CORRIDORS</small><strong className="to-warning-text">{numberText(kpis.high_congestion_corridors)} <span className="to-small">of {traffic.length}</span></strong></div><div><small>ACTIVE AI RECOMMENDATIONS</small><strong className="to-success-text">{numberText(kpis.active_ai_recommendations)} <span className="to-small">awaiting decision</span></strong></div></div>
      <div className="to-page"><div className="to-grid map-split"><Panel title="Salem transit network" subtitle={`Demo observation time: ${timeText(data.as_of)} IST`} actions={<Link to="/network">Explore network <ArrowUpRight size={12} /></Link>}>{network.data ? <TransitMap network={network.data} traffic={traffic} compact /> : <Loading />}<div className="to-disclaimer" style={{ marginTop: 12 }}><Info size={13} /> Eight Salem-inspired illustrative routes. These are not official government routes or GPS bus positions.</div></Panel>
        <Panel title="Traffic intelligence" subtitle="Latest corridor conditions · provenance shown" actions={<Link to="/cctv"><ArrowUpRight size={14} /></Link>}><div>{[...traffic].sort((a, b) => b.congestion_score - a.congestion_score).slice(0, 5).map(corridor => <div className="to-corridor" key={corridor.id}><div className="to-corridor-top"><strong>{corridor.route_ids?.join(', ')} · {String(corridor.name).split('–')[0]}</strong><span className={`to-status ${String(corridor.category).toLowerCase()}`}>{corridor.category}</span></div><p><SourceBadge source={corridor.source} /> <span style={{ marginLeft: 7 }}>{numberText(corridor.congestion_score)} / 100</span></p><div className="to-progress"><span style={{ width: `${Math.min(100, corridor.congestion_score)}%`, background: corridor.congestion_score >= 75 ? '#ff4d67' : corridor.congestion_score >= 50 ? '#ffb020' : '#00e5a0' }} /></div></div>)}</div><p className="to-note">Vehicle density is a scene-based score. Physical vehicle speed and queue length remain unavailable without calibrated observations.</p><Link className="to-button subtle" style={{ marginTop: 16, width: '100%' }} to="/cctv"><CameraIcon /> Open CCTV intelligence</Link></Panel></div>
        <div className="to-grid"><Panel title="Passenger demand trend" subtitle="R02 · synthetic historical boardings per 30 minutes" actions={<Link to="/demand">Forecast demand <ArrowUpRight size={12} /></Link>}><div className="to-chart"><ResponsiveContainer><AreaChart data={chartData}><defs><linearGradient id="dashboard-demand" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#00d9ff" stopOpacity={.22} /><stop offset="100%" stopColor="#00d9ff" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#183850" strokeDasharray="3 4" vertical={false} /><XAxis dataKey="time" tickFormatter={value => new Date(value).toLocaleTimeString('en-IN', { timeZone: 'Asia/Calcutta', hour: '2-digit', minute: '2-digit' })} tick={{ fill: '#678da9', fontSize: 8 }} minTickGap={35} /><YAxis tick={{ fill: '#678da9', fontSize: 8 }} /><Tooltip contentStyle={chartTooltip} labelFormatter={value => timeText(String(value))} /><Area dataKey="demand" name="Synthetic boardings" stroke="#00d9ff" strokeWidth={2} fill="url(#dashboard-demand)" /></AreaChart></ResponsiveContainer></div></Panel>
          <Panel title="Operator review queue" subtitle="Solver recommendations need human approval" actions={<Link to="/recommendations">View all <ArrowUpRight size={12} /></Link>}>{recs.length ? <div className="to-stack">{recs.slice(0, 3).map(rec => <Link key={rec.id} className="to-recommendation" style={{ textDecoration: 'none' }} to={`/recommendations?run=${rec.run_id}`}><div className="to-rec-header"><strong>{rec.route_id} · {rec.current_buses} → {rec.proposed_buses} buses</strong><span className="to-status">{String(rec.status).replace(/_/g, ' ')}</span></div><p style={{ marginBottom: 0 }}>{rec.reason}</p></Link>)}</div> : <Empty title="Your next decision starts here" description="Run optimization to generate fleet and route recommendations from the current forecast and corridor conditions." />}</Panel></div>
        <Panel title="Current route service" subtitle="Fleet totals and capacities are derived from the active simulated plan" actions={<RefreshButton onClick={refresh} />}><RoutePlanTable plan={data.plan} network={network.data ?? undefined} /></Panel>
      </div>
    </>}
  </>;
}
function CameraIcon() { return <MapPin size={13} />; }

interface ScenarioConfig { name: string; fleet_size: number; reserve_fleet: number; bus_capacity: number; horizon_minutes: number; max_headway_minutes: number; demand_multiplier: number; traffic_level: string; event_intensity: string; solver_time_limit_seconds: number; weights: Record<string, number> }
const INITIAL: ScenarioConfig = { name: 'Salem service scenario', fleet_size: 28, reserve_fleet: 4, bus_capacity: 50, horizon_minutes: 60, max_headway_minutes: 30, demand_multiplier: 1, traffic_level: 'current', event_intensity: 'none', solver_time_limit_seconds: 5, weights: { unserved: 1, waiting: 1, operating_cost: 1, traffic_delay: 1, stability: 1 } };
function ScenarioControls({ value, onChange, simulation = false }: { value: ScenarioConfig; onChange: (value: ScenarioConfig) => void; simulation?: boolean }) {
  const field = (key: keyof ScenarioConfig, next: any) => onChange({ ...value, [key]: next });
  return <div className="to-fields"><label className="to-field">Scenario name<input value={value.name} onChange={event => field('name', event.target.value)} maxLength={160} /></label>
    <label className="to-field">Passenger demand<div className="to-pills">{[[.8, '−20%'], [1, 'Normal'], [1.2, '+20%']].map(([factor, label]) => <button key={String(factor)} className={value.demand_multiplier === factor ? 'active' : ''} onClick={() => field('demand_multiplier', factor)}>{label}</button>)}</div><small>Multiplier applied once to the model forecast.</small></label>
    <label className="to-field">Traffic conditions<select aria-label="Traffic conditions" value={value.traffic_level} onChange={event => field('traffic_level', event.target.value)}><option value="current">Current corridor observations</option><option value="low">Low congestion</option><option value="medium">Medium congestion</option><option value="high">High congestion</option></select></label>
    <div className="to-form-row"><label className="to-field">Available fleet<input type="number" aria-label="Available fleet" min={1} max={200} value={value.fleet_size} onChange={event => field('fleet_size', Number(event.target.value))} /></label><label className="to-field">Reserve fleet<input type="number" aria-label="Reserve fleet" min={0} max={100} value={value.reserve_fleet} onChange={event => field('reserve_fleet', Number(event.target.value))} /></label></div>
    {simulation && <div className="to-pills">{[20, 30, 40].map(count => <button key={count} className={value.fleet_size === count ? 'active' : ''} onClick={() => field('fleet_size', count)}>{count} buses</button>)}</div>}
    <label className="to-field">Event intensity<select value={value.event_intensity} aria-label="Event intensity" onChange={event => field('event_intensity', event.target.value)}><option value="none">None · no uplift</option><option value="moderate">Moderate · +10%</option><option value="high">High · +25%</option></select></label>
    <div className="to-form-row"><label className="to-field">Horizon<select aria-label="Optimization horizon" value={value.horizon_minutes} onChange={event => field('horizon_minutes', Number(event.target.value))}>{[30, 60, 120].map(minutes => <option key={minutes} value={minutes}>{minutes} minutes</option>)}</select></label><label className="to-field">Max. headway<input type="number" min={5} max={120} value={value.max_headway_minutes} onChange={event => field('max_headway_minutes', Number(event.target.value))} /></label></div>
    <details><summary className="to-small">Advanced constraints and objective weights</summary><div className="to-fields" style={{ marginTop: 16 }}><div className="to-form-row"><label className="to-field">Seats per bus<input type="number" min={1} max={150} value={value.bus_capacity} onChange={event => field('bus_capacity', Number(event.target.value))} /></label><label className="to-field">Solver limit (s)<input type="number" min={.1} max={30} step={.1} value={value.solver_time_limit_seconds} onChange={event => field('solver_time_limit_seconds', Number(event.target.value))} /></label></div>{Object.entries(value.weights).map(([key, weight]) => <label key={key} className="to-field">{key.replace(/_/g, ' ')} weight<input type="number" min={0} max={100} step={.1} value={weight} onChange={event => field('weights', { ...value.weights, [key]: Number(event.target.value) })} /></label>)}</div></details>
    <div className="to-disclaimer"><ShieldCheck size={13} />Essential routes and stops are hard constraints. Headways and reserves are enforced; unmet demand is reported, never hidden.</div>
  </div>;
}
function useScenario(key: string) {
  const [value, setValue] = useState<ScenarioConfig>(() => { try { const saved = JSON.parse(localStorage.getItem(key) ?? '{}'); return { ...INITIAL, ...saved, weights: { ...INITIAL.weights, ...saved.weights } }; } catch { return { ...INITIAL }; } });
  const [edited, setEdited] = useState(() => { try { return Boolean(localStorage.getItem(key)); } catch { return false; } }); const settings = useResource('/api/settings');
  useEffect(() => { if (settings.data?.settings && !edited) setValue(current => ({ ...current, ...Object.fromEntries(['fleet_size', 'reserve_fleet', 'bus_capacity', 'horizon_minutes', 'max_headway_minutes', 'solver_time_limit_seconds'].map(key => [key, settings.data!.settings[key] ?? current[key as keyof ScenarioConfig]])) })); }, [settings.data, edited]);
  const change = (next: ScenarioConfig) => { setEdited(true); setValue(next); try { localStorage.setItem(key, JSON.stringify(next)); } catch {} };
  return { value, change, settings };
}
export function OptimizationPage() {
  const scenario = useScenario('transitopt-optimization'); const network = useResource<Network>('/api/network'); const [params, setParams] = useSearchParams(); const runId = params.get('run'); const stored = useResource(runId ? `/api/optimization/results/${encodeURIComponent(runId)}` : '/api/settings');
  const [localResult, setLocalResult] = useState<Data | null>(null); const result = localResult ?? (runId ? stored.data : null); const action = useAction(); const refresh = useTransitRefresh();
  useEffect(() => { setLocalResult(null); }, [runId]);
  const run = async () => { const next = await action.run(() => postTransit('/api/optimization/run', scenario.value)); if (next) { setLocalResult(next); setParams({ run: next.id }); refresh(); } };
  return <div className="to-page"><PageHeading title="Route & fleet optimization" description="Find a feasible service plan from ML demand, corridor observations and operational constraints." actions={<SourceBadge source="OPTIMIZATION_RESULT" />} /><ActionNotice action={action} /><ErrorNotice message={network.error || (runId ? stored.error : '')} retry={network.refresh} /><div className="to-grid control-split"><Panel title="Operating assumptions" subtitle="All parameters are sent to the CP-SAT solver"><ScenarioControls value={scenario.value} onChange={scenario.change} /><button className="to-button primary large" style={{ width: '100%', marginTop: 20 }} disabled={action.busy} onClick={run}>{action.busy ? <Loader2 className="animate-spin" size={15} /> : <Sparkles size={15} />} {action.busy ? 'Solving operating plan…' : 'Run optimization'}</button><p className="to-note">This creates a recommendation. Operator approval is required before simulated activation.</p></Panel><div className="to-page">{result ? <><div className="to-action-row"><SourceBadge source="OPTIMIZATION_RESULT" /><span className="to-small">Saved run · {String(result.id).slice(0, 8)}</span><button className="to-button subtle" disabled={action.busy} onClick={() => action.run(() => exportTransit('scenarios', 'csv', result.scenario_id))}><Download size={13} /> Export comparison</button></div><RunResult result={result} network={network.data ?? undefined} /></> : runId && stored.loading ? <Loading label="Loading the saved optimization run…" /> : <><Panel title="Current network"><div className="to-insight"><GitBranch size={24} /><div><strong>Eight routes. One consistent fleet plan.</strong><p>The solver selects a validated corridor and bus allocation for every route, then verifies the entire plan. Changes are explained using demand, capacity, cycle time and congestion.</p></div></div>{network.data && <div style={{ marginTop: 20 }}><TransitMap network={network.data} traffic={network.data.corridors} compact /></div>}</Panel><Empty title="Ready to solve" description="Use the operating assumptions on the left and run optimization. No recommendations are generated until the real solver returns a feasible plan." /></>}</div></div></div>;
}
export function SimulatorPage() {
  const scenario = useScenario('transitopt-simulator'); const network = useResource<Network>('/api/network'); const saved = useResource('/api/simulator/scenarios'); const action = useAction(); const refresh = useTransitRefresh(); const [result, setResult] = useState<Data | null>(null);
  const run = async () => { const next = await action.run(() => postTransit('/api/simulator/run', scenario.value)); if (next) { setResult(next); refresh(); } };
  const load = async (id: string) => { const stored = await action.run(() => transitRequest(`/api/simulator/results/${id}`)); if (stored) setResult(stored.result); };
  return <div className="to-page"><PageHeading eyebrow="SCENARIO LAB" title="What if the city changes?" description="Change demand, congestion and fleet supply. Compare both plans under the same scenario assumptions." actions={<SourceBadge source="SYNTHETIC_DEMO_DATA" />} /><ActionNotice action={action} /><div className="to-grid control-split"><Panel title="Your scenario" subtitle="Selections are preserved on this device"><ScenarioControls value={scenario.value} onChange={scenario.change} simulation /><button className="to-button primary large" style={{ marginTop: 20, width: '100%' }} disabled={action.busy} onClick={run}>{action.busy ? <Loader2 size={14} className="animate-spin" /> : <Play size={14} />} Run optimization</button><p className="to-note">Lower fleet scenarios may be infeasible under the selected maximum headway. The solver reports the conflict rather than dropping essential service.</p></Panel><div className="to-page">{result ? <><div className="to-action-row"><SourceBadge source="OPTIMIZATION_RESULT" /><button className="to-button subtle" onClick={() => action.run(() => exportTransit('scenarios', 'csv', result.scenario_id))}><Download size={13} /> CSV comparison</button><button className="to-button subtle" onClick={() => action.run(() => exportTransit('scenarios', 'json', result.scenario_id))}>JSON result</button></div><RunResult result={result} network={network.data ?? undefined} /></> : <Panel title="Explore service tradeoffs" subtitle="Simulation outcomes are calculated, not prewritten"><div className="to-insight"><SlidersHorizontal size={25} /><div><strong>Try a +20% demand scenario.</strong><p>Select a demand increase, then run the optimizer to see which services need more capacity. Fleet availability and strict service constraints can limit the achievable coverage.</p></div></div>{network.data && <div style={{ marginTop: 18 }}><TransitMap network={network.data} traffic={network.data.corridors} compact /></div>}</Panel>}</div></div><Panel title="Saved scenarios" subtitle="Persisted inputs, solver status and comparison results" actions={<RefreshButton onClick={saved.refresh} />}><ErrorNotice message={saved.error} />{rows(saved.data?.scenarios).length ? <div className="to-data-table-wrap"><table className="to-data-table"><thead><tr><th>Scenario</th><th>Recorded</th><th>Fleet</th><th>Demand multiplier</th><th>Status</th><th /></tr></thead><tbody>{rows(saved.data?.scenarios).map(item => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{timeText(item.timestamp)}</td><td>{item.inputs?.fleet_size}</td><td>{item.inputs?.demand_multiplier}×</td><td>{item.result?.solver_status ?? (item.activated ? 'Activated' : 'Saved')}</td><td><button className="to-button subtle" onClick={() => load(item.id)} disabled={action.busy}>View result</button></td></tr>)}</tbody></table></div> : <Empty title="No scenarios yet" description="Run a scenario to save its inputs, baseline, optimized result and calculated comparison." />}</Panel></div>;
}
export function NetworkPage() {
  const network = useResource<Network>('/api/network'); const traffic = useResource('/api/traffic/corridors'); const [routeId, setRouteId] = useState('R02'); const [variant, setVariant] = useState('existing');
  const recommendations = useResource('/api/recommendations'); const selected = network.data?.routes.find(route => route.id === routeId); const recommendation = rows(recommendations.data?.recommendations).find(rec => rec.route_id === routeId && rec.status !== 'rejected');
  const variantPlan = selected ? { routes: [{ route_id: routeId, buses: variant === 'optimized' && recommendation ? recommendation.proposed_buses : selected.current_buses, variant_id: variant === 'optimized' ? recommendation?.proposed_variant_id ?? selected.current_variant_id : variant }] } : undefined;
  return <div className="to-page"><PageHeading title="Salem transit network" description="Explore route geometry, essential stops, camera locations and validated illustrative alternatives." actions={<RefreshButton onClick={network.refresh} />} /><ErrorNotice message={network.error || traffic.error} retry={network.refresh} />{network.loading && !network.data ? <Loading /> : network.data && <div className="to-grid map-split"><Panel title="Routes, corridors & service" subtitle={`Synthetic observation time: ${timeText(network.data.as_of)} IST`} actions={<SourceBadge source="SYNTHETIC_DEMO_DATA" />}><TransitMap network={network.data} traffic={rows(traffic.data?.corridors)} selectedRoute={routeId} onSelectRoute={id => { setRouteId(id); setVariant('existing'); }} plan={variant === 'existing' ? undefined : variantPlan} /><p className="to-note">{network.data.disclaimer} The map uses canvas coordinates. Bus markers show illustrative assignments, not real-time GPS.</p></Panel><Panel title={selected ? `${selected.id} · Route details` : 'Select a route'} subtitle={selected?.name}>{selected ? <><div className="to-pills" style={{ marginBottom: 20 }}>{[['existing', 'Existing'], ['alternative', 'Alternative'], ['optimized', 'Optimized']].map(([id, label]) => <button key={id} className={variant === id ? 'active' : ''} disabled={id === 'optimized' && !recommendation} onClick={() => setVariant(id)}>{label}</button>)}</div><dl className="to-details"><div><dt>Current allocation</dt><dd>{selected.current_buses} buses</dd></div><div><dt>Seats per bus</dt><dd>{selected.bus_capacity}</dd></div><div><dt>Minimum service</dt><dd>{selected.min_buses} bus</dd></div><div><dt>Maximum headway</dt><dd>{(selected as any).effective_max_headway_minutes ?? selected.max_headway_minutes} min</dd></div><div><dt>Free-flow round-trip cycle</dt><dd>{selected.variants.find(v => v.id === (variant === 'optimized' ? recommendation?.proposed_variant_id : variant))?.cycle_minutes} min</dd></div><div><dt>Corridor</dt><dd>{selected.corridor_id}</dd></div></dl><h3 style={{ fontSize: 11, margin: '23px 0 12px' }}>Essential stop sequence</h3><div className="to-stack">{selected.stop_ids.map((id, index) => <div className="to-bullet" key={id}><span style={{ color: selected.color }}>{String(index + 1).padStart(2, '0')}</span><span>{network.data!.stops.find(stop => stop.id === id)?.name}<small style={{ display: 'block', color: '#587a96' }}>Essential service preserved</small></span></div>)}</div>{recommendation && <div className="to-rec-evidence" style={{ marginTop: 20 }}><strong>Solver recommendation</strong><p>{recommendation.reason}</p><Link to={`/recommendations?run=${recommendation.run_id}`} className="to-button subtle">Review plan <ChevronRight size={12} /></Link></div>}</> : <Empty title="Explore any of eight routes" description="Select a colored route or route ID below the map to inspect stops, service and alternatives." />}</Panel></div>}</div>;
}
export function RecommendationsPage() {
  const [params, setParams] = useSearchParams(); const all = useResource('/api/recommendations'); const network = useResource<Network>('/api/network'); const [filter, setFilter] = useState('all'); const [note, setNote] = useState(''); const action = useAction(); const refresh = useTransitRefresh();
  const recs = rows(all.data?.recommendations); const runIds = [...new Set(recs.map(rec => rec.run_id))]; const selectedRun = params.get('run') ?? runIds[0] ?? ''; const run = useResource(selectedRun ? `/api/optimization/results/${encodeURIComponent(selectedRun)}` : '/api/settings');
  const selected = recs.filter(rec => rec.run_id === selectedRun); const displayed = selected.filter(rec => filter === 'all' || rec.status === filter);
  const activated = selected.some(rec => rec.status === 'activated') || Boolean(run.data?.activated); const rejected = selected.some(rec => rec.status === 'rejected'); const allApproved = selected.length ? selected.every(rec => rec.status === 'approved') : Boolean(run.data?.plan_approved); const planReady = Boolean(selectedRun && run.data?.feasible && run.data?.id === selectedRun && !run.loading); const visibleRunIds = [...new Set([selectedRun, ...runIds].filter(Boolean))];
  const change = async (id: string, verb: string) => { await action.run(() => postTransit(`/api/recommendations/${id}/${verb}`, { note }), `Recommendation ${verb === 'approve' ? 'approved' : 'rejected'} and action recorded.`); refresh(); };
  const approvePlan = async () => { await action.run(() => postTransit(`/api/optimization/results/${selectedRun}/approve`, { note }), 'The complete recommendation plan is approved. Simulated activation remains a separate operator action.'); refresh(); };
  const activate = async () => { await action.run(() => postTransit(`/api/optimization/results/${selectedRun}/activate-simulation`), 'Approved plan activated in simulation. Route assignments and fleet records updated atomically.'); refresh(); };
  return <div className="to-page"><PageHeading eyebrow="HUMAN-IN-CONTROL WORKFLOW" title="Recommendations & approval" description="Review the evidence, approve the complete operating plan, then activate it in simulation." actions={<Link className="to-button primary" to="/optimization"><Sparkles size={14} /> New optimization</Link>} /><ActionNotice action={action} /><ErrorNotice message={all.error || (selectedRun ? run.error : '')} retry={all.refresh} />
    <div className="to-workflow"><div><span>01</span>AI recommendation</div><div><span>02</span>Operator review</div><div><span>03</span>Plan approval</div><div><span>04</span>Simulated activation</div></div>
    {!recs.length && !selectedRun && !all.loading ? <Empty title="No recommendations to review" description="Run route optimization or a what-if scenario. A feasible solver result creates reviewable recommendations for changed routes." /> : <>
      <Panel title="Select an operating plan" subtitle="Individual route decisions belong to one fleet-consistent plan"><div className="to-form-row"><label className="to-field">Optimization run<select aria-label="Recommendation plan" value={selectedRun} onChange={event => setParams({ run: event.target.value })}>{visibleRunIds.map(id => <option key={id} value={id}>Run {String(id).slice(0, 8)} · {recs.find(rec => rec.run_id === id)?.timestamp ? timeText(recs.find(rec => rec.run_id === id)!.timestamp) : 'Saved scenario'}</option>)}</select></label><label className="to-field">Operator note<input placeholder="Optional rationale for the audit record" value={note} maxLength={1000} onChange={event => setNote(event.target.value)} /></label></div><div className="to-action-row" style={{ marginTop: 18 }}><button className="to-button success" disabled={action.busy || !planReady || rejected || activated || allApproved} onClick={approvePlan}><ShieldCheck size={14} /> Approve complete plan</button><button className="to-button primary" disabled={action.busy || !planReady || !allApproved || activated} onClick={activate}><Play size={14} /> Activate in simulation</button><span className="to-small">{activated ? 'This plan is active in simulation.' : rejected ? 'A rejected route blocks this plan. Run a revised optimization.' : allApproved ? 'All changed routes approved. Ready for simulated activation.' : 'Activation stays disabled until every changed route is approved.'}</span></div></Panel>
      <div className="to-tabs">{[['all', 'All decisions'], ['pending_review', 'Pending review'], ['approved', 'Approved'], ['rejected', 'Rejected'], ['activated', 'Activated']].map(([value, label]) => <button key={value} className={filter === value ? 'active' : ''} onClick={() => setFilter(value)}>{label}</button>)}</div>
      <div className="to-grid">{displayed.map(rec => <div key={rec.id} className="to-recommendation"><div className="to-rec-header"><strong>{rec.route_id} · {network.data?.routes.find(route => route.id === rec.route_id)?.name}</strong><span className={`to-status ${rec.status}`}>{String(rec.status).replace(/_/g, ' ')}</span></div><div className="to-rec-change"><span>{rec.current_buses} buses</span><ArrowRight size={14} /><b>{rec.proposed_buses} buses</b><SourceBadge source="OPTIMIZATION_RESULT" /></div><p>{rec.reason}</p><dl className="to-details"><div><dt>Proposed corridor</dt><dd>{rec.proposed_variant_id}</dd></div><div><dt>Recorded</dt><dd>{timeText(rec.timestamp)}</dd></div></dl>{rec.status === 'pending_review' && <div className="to-action-row" style={{ marginTop: 18 }}><button className="to-button success" disabled={action.busy} onClick={() => change(rec.id, 'approve')}><Check size={13} /> Approve</button><button className="to-button danger" disabled={action.busy} onClick={() => change(rec.id, 'reject')}><X size={13} /> Reject</button></div>}</div>)}</div>
      {run.data?.feasible && <ComparisonPanel result={run.data} />}
      <div className="to-disclaimer"><Info size={14} />Activation updates only the local simulated plan. Stale plans, infeasible allocations and rejected or unapproved changes are refused by the backend.</div>
    </>}
  </div>;
}
