import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { DEMO_STEPS, useDemoRecorder } from '../../components/DemoRecorder';
import { PageHeading, Panel, ErrorNotice, Loading } from '../../components/transit/Shared';
import { postTransit, type Data } from '../../services/transit';

export default function RecordDemoPage(){
  const recorder=useDemoRecorder();
  function subtitles(){const url=URL.createObjectURL(new Blob([recorder.srt],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='TransitOpt-Full-App-Captions.srt';a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <div className="to-page"><PageHeading eyebrow="CAPTIONED SCREEN RECORDING" title="Record the full ML app" description="The guided tour opens the actual application modules and runs two recorded-sample ML detections. Pause to demonstrate your webcam, route selection or other controls."/><ErrorNotice message={recorder.error}/><Panel title="Capture this application tab" subtitle={`About ${Math.ceil(DEMO_STEPS.reduce((sum,s)=>sum+s[2],0)/60)} minutes automatically · extend any section with Pause tour`}><p className="to-note">Sign-in is already complete. Click Record guided tour and choose this TransitOpt tab in the browser chooser. Captions appear on-screen and also download as SRT. Audio is off. Recording stays in this browser and is never uploaded.</p><p className="to-note">The tour processes a bundled recorded image twice and saves normal analysis records. It does not approve plans, activate simulation changes, or request webcam/GPS permission automatically. For a full live demonstration, pause on Live camera and Passenger navigation, then use their controls.</p><div className="demo-record-downloads"><button className="to-button primary" disabled={recorder.active} onClick={()=>recorder.start(true)}>Record guided tour</button><button className="to-button" disabled={recorder.active} onClick={()=>recorder.start(false)}>Preview tour without recording</button><Link className="to-button" to="/ml">Open ML workspace</Link></div>{recorder.videoUrl&&<><video className="demo-record-preview" src={recorder.videoUrl} controls/><div className="demo-record-downloads"><a className="to-button primary" href={recorder.videoUrl} download={`TransitOpt-Full-App-Recording.${recorder.extension}`}>Download screen recording</a><button className="to-button" onClick={subtitles}>Download captions (.srt)</button></div><p className="to-note">Download before closing or refreshing this tab. Use Convert-Recording-To-MP4.bat to convert a WebM recording if needed.</p></>}{!recorder.videoUrl&&recorder.srt&&<button className="to-button" onClick={subtitles}>Download preview captions</button>}</Panel><Panel title="Tour chapters"><div className="demo-record-steps">{DEMO_STEPS.map((s,i)=><div key={s[0]}><strong>{i+1}. {s[0]}</strong><p>{s[1]}</p></div>)}</div></Panel></div>;
}

export function RecordedSamplePage(){
  const {mode}=useParams();const interior=mode==='interior';
  const [result,setResult]=useState<Data|null>(null),[error,setError]=useState('');
  useEffect(()=>{let active=true;setResult(null);setError('');postTransit(`/api/vision/samples/bus-image/analyze?camera_id=${interior?'BUS_CAM_001':'CAM02'}`).then(data=>{if(active)setResult(data);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[interior]);
  return <div className="to-page"><PageHeading eyebrow="REAL INFERENCE · RECORDED SAMPLE" title={interior?'Person detector / bus crowd pipeline':'Road vehicle detector'} description="Bundled Ultralytics street image. This demonstrates actual model execution on a recorded sample; it is not live traffic or real bus interior footage."/><ErrorNotice message={error}/>{!result&&!error?<Loading label="Running YOLO on the recorded sample…"/>:result&&<Panel><div className="demo-record-sample"><img alt="Actual model annotated sample" src={result.annotated_image ?? result.processed_image}/><div><h2>Actual detection result</h2><pre>{JSON.stringify(result.counts,null,2)}</pre><p className="to-note">Model: {result.model_info?.filename ?? result.model_info?.name ?? 'Existing configured YOLO detector'}</p><p className="to-note">Source: recorded image · {result.source}</p><p className="to-note">{interior?'Only visible people feed the crowd estimate. This street image tests the person-only pipeline; use authorized interior footage for a real bus.':'Vehicle counts produce a scene-pressure estimate. Recorded samples are excluded from live route alerts.'}</p><Link className="to-button" to="/cctv">Open interactive CCTV analysis</Link></div></div></Panel>}</div>;
}
